### ISSUE TITLE
apiTesting folder

### ISSUE THREAD

**Issue by ds3031** [reallymello/nightwatchTutorials#99]
Hi,

I cloned repo, cd to apiTesting folder, npm install, npx nightwatch and I get this err:

` ✖  default: restfulBookerLocal.ts  
     Error                                                                                                                            
       Cannot find module '../../restfulBooker/restful-booker/app'                                                                    
    Require stack:                                                                                                                    
    - /Users/nameus/Documents/apiTesting-mello/nightwatchTutorials/apiTesting/nightwatch/tests/restfulBookerLocal.ts                
    - /Users/nameus/Documents/apiTesting-mello/nightwatchTutorials/apiTesting/node_modules/nightwatch/lib/utils/requireModule.js    
    - /Users/nameus/Documents/apiTesting-mello/nightwatchTutorials/apiTesting/node_modules/nightwatch/lib/utils/index.js            
    - /Users/nameus/Documents/apiTesting-mello/nightwatchTutorials/apiTesting/node_modules/nightwatch/bin/nightwatch                
                                                                                                                                      
        Error location:                                                                                                               
        /Users/nameus/Documents/apiTesting-mello/nightwatchTutorials/apiTesting/nightwatch/tests/restfulBookerLocal.ts:             
         7 | import '@nightwatch/apitesting';                                                                                         
         8 |                                                                                                                          
         9 | const server = require('../../restfulBooker/restful-booker/app');                                                        
         10 |                                                                                                                         
         11 | const bookerTests: NightwatchTests = {`

**Comment by reallymello** [comment]
Hi @ds3031 , can you try to cd into apiTesting/restfulBooker/ and do an extra `npm install` in there and let me know if that works?

```sh
PS C:\Projects\nightwatchTutorials\apiTesting> cd .\restfulBooker\
PS C:\Projects\nightwatchTutorials\apiTesting\restfulBooker> npm install
```

**Comment by ds3031** [comment]
Hi,

It didn't help. nvm examples that works OK are enough

Thank you
